/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merge;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Arcane
 */
public class BathcM extends javax.swing.JFrame {

    int rowIndx = -1;
    DefaultTableModel mod,model;
    Connection con;
    String task = "Edit";

    /**
     * Creates new form BathcM
     */
    public BathcM() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        try {
            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ACMS;selectMethod=cursor", "sa", "123456");
        } catch (SQLException ex) {
            Logger.getLogger(BathcM.class.getName()).log(Level.SEVERE, null, ex);
        }

        populateTable();
        populateCourse();
        //populateBatch();
        //populateDistrict();

        saveBatch.setVisible(false);
        cancelBatch.setVisible(false);
        //course.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        cancelBatch = new javax.swing.JButton();
        batchId = new javax.swing.JTextField();
        idlab = new javax.swing.JLabel();
        editBatch = new javax.swing.JButton();
        saveBatch = new javax.swing.JButton();
        returnBatch = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        batchName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        course = new javax.swing.JComboBox<>();
        addBatch = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        batchTable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1374, 792));
        jPanel1.setName(""); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1374, 792));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 50));

        jTabbedPane2.setBackground(new java.awt.Color(0, 153, 255));
        jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel9.setBackground(new java.awt.Color(0, 153, 255));

        cancelBatch.setBackground(new java.awt.Color(0, 168, 247));
        cancelBatch.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        cancelBatch.setText("Cancel");
        cancelBatch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelBatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBatchActionPerformed(evt);
            }
        });

        batchId.setEditable(false);
        batchId.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        batchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchIdActionPerformed(evt);
            }
        });

        idlab.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        idlab.setText("ID                    :");

        editBatch.setBackground(new java.awt.Color(0, 168, 247));
        editBatch.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        editBatch.setText("Edit");
        editBatch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editBatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBatchActionPerformed(evt);
            }
        });

        saveBatch.setBackground(new java.awt.Color(0, 168, 247));
        saveBatch.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        saveBatch.setText("Save");
        saveBatch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveBatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBatchActionPerformed(evt);
            }
        });

        returnBatch.setBackground(new java.awt.Color(0, 168, 247));
        returnBatch.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        returnBatch.setText("Return");
        returnBatch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnBatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBatchActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel8.setText("Batch Name  :");

        batchName.setEditable(false);
        batchName.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        batchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchNameActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel9.setText("Course           :");

        course.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        addBatch.setBackground(new java.awt.Color(0, 168, 247));
        addBatch.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        addBatch.setText("Add");
        addBatch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addBatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBatchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(cancelBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(addBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idlab, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(batchId, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(4, 4, 4)
                                .addComponent(batchName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(returnBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batchId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batchName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBatch)
                    .addComponent(cancelBatch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBatch)
                    .addComponent(addBatch))
                .addGap(88, 88, 88)
                .addComponent(returnBatch)
                .addGap(89, 89, 89))
        );

        jTabbedPane2.addTab("tab3", jPanel9);

        jPanel2.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 360, 800));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 800));

        jPanel15.setBackground(new java.awt.Color(0, 168, 247));

        title.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Batch Management");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(641, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 1030, 50));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        batchTable.setAutoCreateRowSorter(true);
        batchTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        batchTable.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        batchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        batchTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        batchTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        batchTable.setGridColor(new java.awt.Color(255, 255, 255));
        batchTable.setRowHeight(70);
        batchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batchTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(batchTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(918, 918, 918))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel6);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 1010, 700));

        jTextField1.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 190, 50));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel1.setText("Search:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 100, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBatchActionPerformed
        // TODO add your handling code here:
        //jTabbedPane1.setSelectedIndex(1);
        //populateProfile();
        editBatch.setVisible(true);
        addBatch.setVisible(true);
        returnBatch.setVisible(true);
        saveBatch.setVisible(false);
        cancelBatch.setVisible(false);
        batchId.setText("");
        batchName.setText("");
        batchId.setVisible(true);
        idlab.setVisible(true);
        course.setSelectedIndex(0);
    }//GEN-LAST:event_cancelBatchActionPerformed

    private void batchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchIdActionPerformed

    private void editBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBatchActionPerformed
        // TODO add your handling code here:
        task = "Edit";
        editBatch.setVisible(false);
        addBatch.setVisible(false);
        returnBatch.setVisible(false);
        saveBatch.setVisible(true);
        cancelBatch.setVisible(true);
        batchId.setVisible(false);
        idlab.setVisible(false);
    }//GEN-LAST:event_editBatchActionPerformed

    private void saveBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBatchActionPerformed
        // TODO add your handling code here:
        String id = batchId.getText();
        String name = batchName.getText().toString();
        String cor = course.getSelectedItem().toString();
        String corid = "";

        try {
            // Your database connections 
            Statement st = con.createStatement();

            String quer = "SELECT * FROM COURSES WHERE course_name=?";
            PreparedStatement statement = con.prepareStatement(quer);
            statement.setString(1, cor);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                corid = rs.getString(1);
            }
            //con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }

        if (task.equals("Edit")) {
            try {
                String quer = "UPDATE BATCHS set batch_name=?,course_id=? WHERE batch_id=?";
                PreparedStatement statement = con.prepareStatement(quer);
                statement.setString(1, name);
                statement.setString(2, corid);
                statement.setString(3, id);
                statement.executeUpdate();
                populateTable();
                JOptionPane.showMessageDialog(this, "Successfully Updated");
                editBatch.setVisible(true);
                addBatch.setVisible(true);
                returnBatch.setVisible(true);
                saveBatch.setVisible(false);
                cancelBatch.setVisible(false);
                batchId.setText("");
                batchName.setText("");
                course.setSelectedIndex(0);
                batchId.setVisible(true);
                idlab.setVisible(true);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        } else {

            try {
                String quer = "INSERT INTO BATCHS VALUES(?,?)";
                PreparedStatement statement = con.prepareStatement(quer);
                statement.setString(1, name);
                statement.setString(2, corid);
                statement.executeUpdate();
                populateTable();
                JOptionPane.showMessageDialog(this, "Successfully Added");
                editBatch.setVisible(true);
                addBatch.setVisible(true);
                returnBatch.setVisible(true);
                saveBatch.setVisible(false);
                cancelBatch.setVisible(false);
                batchId.setText("");
                batchName.setText("");
                course.setSelectedIndex(0);
                batchId.setVisible(true);
                idlab.setVisible(true);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_saveBatchActionPerformed

    private void returnBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBatchActionPerformed
        // TODO add your handling code here:
        adminLayout obj = new adminLayout();
        obj.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_returnBatchActionPerformed

    private void batchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchNameActionPerformed

    private void batchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batchTableMouseClicked
        // TODO add your handling code here:
        mod = (DefaultTableModel) batchTable.getModel();
        rowIndx = batchTable.getSelectedRow();
        batchId.setText(mod.getValueAt(rowIndx, 0).toString());
        batchName.setText(mod.getValueAt(rowIndx, 1).toString());
        String corSelect = mod.getValueAt(rowIndx, 2).toString();
        for (int i = 0; i < course.getItemCount(); i++) {
            if (course.getItemAt(i).toString().equals(corSelect)) {
                course.setSelectedIndex(i);
                break;
            }
        }
    }//GEN-LAST:event_batchTableMouseClicked

    private void addBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBatchActionPerformed
        // TODO add your handling code here:
        editBatch.setVisible(false);
        addBatch.setVisible(false);
        returnBatch.setVisible(false);
        saveBatch.setVisible(true);
        cancelBatch.setVisible(true);
        task = "Add";
        batchId.setText("");
        batchName.setText("");
        batchId.setVisible(false);
        idlab.setVisible(false);
    }//GEN-LAST:event_addBatchActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        String s = jTextField1.getText();
        searchRecordApprove(s);
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BathcM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BathcM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BathcM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BathcM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BathcM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBatch;
    private javax.swing.JTextField batchId;
    private javax.swing.JTextField batchName;
    private javax.swing.JTable batchTable;
    private javax.swing.JButton cancelBatch;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JButton editBatch;
    private javax.swing.JLabel idlab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton returnBatch;
    private javax.swing.JButton saveBatch;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
    public void populateTable() {
        try {
            String quer = "SELECT batch_id,batch_name,course_name FROM BATCHS B INNER JOIN COURSES C ON C.course_id=B.course_id";
            ResultSet resultSet;
            PreparedStatement statement = con.prepareStatement(quer);
            resultSet = statement.executeQuery();
            batchTable.setModel(DbUtils.resultSetToTableModel(resultSet));
            searchRecordApprove("");
        } catch (SQLException ex) {
            Logger.getLogger(studentLayout.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void populateCourse() {
        try {
            // Your database connections 
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM COURSES");
            while (rs.next()) {
                course.addItem(rs.getString(2));
            }
            //con.close();
        } catch (SQLException e) {
            System.out.println("Error" + e);
        }
    }
    public void searchRecordApprove(String str){
        model = (DefaultTableModel) batchTable.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        batchTable.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter("(?i)" + str));

    }

}
