/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merge;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Arcane
 */
public class subjectM extends javax.swing.JFrame {

    int rowIndx = -1;
    DefaultTableModel mod;
    Connection con;
    String task = "Edit";
    String cID="";

    /**
     * Creates new form subjectM
     */
    /*void getID(String ID) {
        cID = ID;
    }*/
    
    public subjectM() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        try {
            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ACMS;selectMethod=cursor", "sa", "123456");
        } catch (SQLException ex) {
            Logger.getLogger(subjectM.class.getName()).log(Level.SEVERE, null, ex);
        }
        populateTable();
        //populateBatch();
        //populateDistrict();

        saveSubject.setVisible(false);
        cancelSubject.setVisible(false);
        //JOptionPane.showMessageDialog(this, cID);
    }
    public subjectM(String id) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        cID = id;
        try {
            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ACMS;selectMethod=cursor", "sa", "123456");
        } catch (SQLException ex) {
            Logger.getLogger(subjectM.class.getName()).log(Level.SEVERE, null, ex);
        }
        populateTable();
        //populateBatch();
        //populateDistrict();

        saveSubject.setVisible(false);
        cancelSubject.setVisible(false);
       // JOptionPane.showMessageDialog(this, cID);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        subjectName = new javax.swing.JTextField();
        subjectId = new javax.swing.JTextField();
        idlab = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cancelSubject = new javax.swing.JButton();
        editSubject = new javax.swing.JButton();
        saveSubject = new javax.swing.JButton();
        returnSubject = new javax.swing.JButton();
        addSubject = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        subjectTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1374, 792));
        jPanel1.setName(""); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1374, 792));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 50));

        jTabbedPane2.setBackground(new java.awt.Color(0, 153, 255));
        jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel9.setBackground(new java.awt.Color(0, 153, 255));

        subjectName.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        subjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectNameActionPerformed(evt);
            }
        });

        subjectId.setEditable(false);
        subjectId.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        subjectId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectIdActionPerformed(evt);
            }
        });

        idlab.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        idlab.setText("ID           :");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel2.setText("Name    :");

        cancelSubject.setBackground(new java.awt.Color(0, 168, 247));
        cancelSubject.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        cancelSubject.setText("Cancel");
        cancelSubject.setAutoscrolls(true);
        cancelSubject.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelSubject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSubjectActionPerformed(evt);
            }
        });

        editSubject.setBackground(new java.awt.Color(0, 168, 247));
        editSubject.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        editSubject.setText("Edit");
        editSubject.setAutoscrolls(true);
        editSubject.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editSubject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSubjectActionPerformed(evt);
            }
        });

        saveSubject.setBackground(new java.awt.Color(0, 168, 247));
        saveSubject.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        saveSubject.setText("Save");
        saveSubject.setAutoscrolls(true);
        saveSubject.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveSubject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSubjectActionPerformed(evt);
            }
        });

        returnSubject.setBackground(new java.awt.Color(0, 168, 247));
        returnSubject.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        returnSubject.setText("Return");
        returnSubject.setAutoscrolls(true);
        returnSubject.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnSubject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnSubjectActionPerformed(evt);
            }
        });

        addSubject.setBackground(new java.awt.Color(0, 168, 247));
        addSubject.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        addSubject.setText("Add");
        addSubject.setAutoscrolls(true);
        addSubject.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addSubject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(cancelSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(addSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idlab)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(subjectId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjectName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(returnSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subjectId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idlab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(183, 183, 183)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveSubject)
                    .addComponent(cancelSubject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editSubject)
                    .addComponent(addSubject))
                .addGap(68, 68, 68)
                .addComponent(returnSubject)
                .addGap(76, 76, 76))
        );

        jTabbedPane2.addTab("tab3", jPanel9);

        jPanel2.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 360, 800));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 800));

        jPanel15.setBackground(new java.awt.Color(0, 168, 247));

        title.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Subject Management");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(641, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(title)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 1030, 60));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        subjectTable.setAutoCreateRowSorter(true);
        subjectTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        subjectTable.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        subjectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        subjectTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        subjectTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        subjectTable.setGridColor(new java.awt.Color(255, 255, 255));
        subjectTable.setRowHeight(70);
        subjectTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(subjectTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(918, 918, 918))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel6);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 1010, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectNameActionPerformed

    private void subjectIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectIdActionPerformed

    private void cancelSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSubjectActionPerformed
        // TODO add your handling code here:
        //jTabbedPane1.setSelectedIndex(1);
        //populateProfile();
        editSubject.setVisible(true);
        addSubject.setVisible(true);
        returnSubject.setVisible(true);
        saveSubject.setVisible(false);
        cancelSubject.setVisible(false);
        subjectId.setText("");
        subjectName.setText("");
        subjectId.setVisible(true);
        idlab.setVisible(true);
    }//GEN-LAST:event_cancelSubjectActionPerformed

    private void editSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSubjectActionPerformed
        // TODO add your handling code here:
        task = "Edit";
        editSubject.setVisible(false);
        addSubject.setVisible(false);
        returnSubject.setVisible(false);
        saveSubject.setVisible(true);
        cancelSubject.setVisible(true);
        subjectId.setVisible(false);
        idlab.setVisible(false);
    }//GEN-LAST:event_editSubjectActionPerformed

    private void saveSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSubjectActionPerformed
        // TODO add your handling code here:
        String id = subjectId.getText();
        String name = subjectName.getText().toString();

        if (task.equals("Edit")) {
            try {
                String quer = "UPDATE SUBJECTS set subject_name=? WHERE subject_id=?";
                PreparedStatement statement = con.prepareStatement(quer);
                statement.setString(1, name);
                statement.setString(2, id);
                statement.executeUpdate();
                populateTable();
                JOptionPane.showMessageDialog(this, "Successfully Updated");
                editSubject.setVisible(true);
                addSubject.setVisible(true);
                returnSubject.setVisible(true);
                saveSubject.setVisible(false);
                cancelSubject.setVisible(false);
                subjectId.setText("");
                subjectName.setText("");
                subjectId.setVisible(true);
                idlab.setVisible(true);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        } else {

            try {
                String quer = "INSERT INTO SUBJECTS(subject_name,course_id) VALUES(?,?)";
                PreparedStatement statement = con.prepareStatement(quer);
                statement.setString(1, name);
                statement.setString(2, cID);
                statement.executeUpdate();
                populateTable();
                JOptionPane.showMessageDialog(this, "Successfully Added");
                editSubject.setVisible(true);
                addSubject.setVisible(true);
                returnSubject.setVisible(true);
                saveSubject.setVisible(false);
                cancelSubject.setVisible(false);
                subjectId.setText("");
                subjectName.setText("");
                subjectId.setVisible(true);
                idlab.setVisible(true);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_saveSubjectActionPerformed

    private void returnSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnSubjectActionPerformed

    private void subjectTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectTableMouseClicked
        // TODO add your handling code here:
        mod = (DefaultTableModel) subjectTable.getModel();
        rowIndx = subjectTable.getSelectedRow();
        subjectId.setText(mod.getValueAt(rowIndx, 0).toString());
        subjectName.setText(mod.getValueAt(rowIndx, 1).toString());
    }//GEN-LAST:event_subjectTableMouseClicked

    private void addSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectActionPerformed
        // TODO add your handling code here:
        editSubject.setVisible(false);
        addSubject.setVisible(false);
        returnSubject.setVisible(false);
        saveSubject.setVisible(true);
        cancelSubject.setVisible(true);
        task = "Add";
        subjectId.setText("");
        subjectName.setText("");
        subjectId.setVisible(false);
        idlab.setVisible(false);
    }//GEN-LAST:event_addSubjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subjectM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subjectM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subjectM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subjectM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subjectM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubject;
    private javax.swing.JButton cancelSubject;
    private javax.swing.JButton editSubject;
    private javax.swing.JLabel idlab;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton returnSubject;
    private javax.swing.JButton saveSubject;
    private javax.swing.JTextField subjectId;
    private javax.swing.JTextField subjectName;
    private javax.swing.JTable subjectTable;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
    public void populateTable() {
        try {
            String quer = "SELECT subject_id,subject_name FROM SUBJECTS WHERE course_id=?";
            ResultSet resultSet;
            PreparedStatement statement = con.prepareStatement(quer);
            statement.setString(1, cID);
            resultSet = statement.executeQuery();
            subjectTable.setModel(DbUtils.resultSetToTableModel(resultSet));

        } catch (SQLException ex) {
            Logger.getLogger(subjectM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
